name: endernote
description: "Your versatile note-taking companion. Craft, create, and unleash your ideas with ease!"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  flutter_markdown: ^0.7.3
  ficonsax: ^0.0.3
  easy_url_launcher: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/
