name: Flutter Mobile Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_android:
    name: 🤖 Build Android APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.0"
          channel: "stable"
      - run: flutter pub get
      - run: flutter build apk
      - uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
  build_ios:
    name: 🎉 Build iOS IPA
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.0"
          channel: "stable"
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - run: mkdir -p Payload
      - run: mv build/ios/iphoneos/Runner.app Payload
      - run: zip -r app.ipa Payload
      - uses: actions/upload-artifact@v3
        with:
          name: release-ipa
          path: app.ipa
