name: Flutter Mobile Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_android:
    name: 🤖 Build Android APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"
          channel: "stable"
      - run: flutter pub get
      - run: flutter build apk
      - name: 📦 Create GitHub Release for Android
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}-android
          release_name: "Android Release v1.0.${{ github.run_number }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Android APK
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: build/app/outputs/flutter-apk/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive

  build_ios:
    name: 🎉 Build iOS IPA
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"
          channel: "stable"
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - run: mkdir -p Payload
      - run: mv build/ios/iphoneos/Runner.app Payload
      - run: zip -r app.ipa Payload
      - name: 📦 Create GitHub Release for iOS
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}-ios
          release_name: "iOS Release v1.0.${{ github.run_number }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload iOS IPA
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: app.ipa
          asset_name: app.ipa
          asset_content_type: application/octet-stream
