name: Flutter Mobile Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_android:
    name: 🤖 Build Android APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"
          channel: "stable"
      - run: flutter pub get
      - run: flutter build apk
      - uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build_ios:
    name: 🎉 Build iOS IPA
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"
          channel: "stable"
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - run: mkdir -p Payload
      - run: mv build/ios/iphoneos/Runner.app Payload
      - run: zip -r app.ipa Payload
      - uses: actions/upload-artifact@v3
        with:
          name: release-ipa
          path: app.ipa

  create_release:
    name: 📦 Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build_android, build_ios]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/create-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: "Release v1.0.${{ github.run_number }}"
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/flutter-apk/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
      - uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app.ipa
          asset_name: app.ipa
          asset_content_type: application/octet-stream
